//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]


    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Entities”部分中的连接字符串初始化新 Entities 对象。
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<L_Classs> L_Classs
        {
            get
            {
                if ((_L_Classs == null))
                {
                    _L_Classs = base.CreateObjectSet<L_Classs>("L_Classs");
                }
                return _L_Classs;
            }
        }
        private ObjectSet<L_Classs> _L_Classs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<L_Feedback> L_Feedback
        {
            get
            {
                if ((_L_Feedback == null))
                {
                    _L_Feedback = base.CreateObjectSet<L_Feedback>("L_Feedback");
                }
                return _L_Feedback;
            }
        }
        private ObjectSet<L_Feedback> _L_Feedback;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<L_Form> L_Form
        {
            get
            {
                if ((_L_Form == null))
                {
                    _L_Form = base.CreateObjectSet<L_Form>("L_Form");
                }
                return _L_Form;
            }
        }
        private ObjectSet<L_Form> _L_Form;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<L_Newss> L_Newss
        {
            get
            {
                if ((_L_Newss == null))
                {
                    _L_Newss = base.CreateObjectSet<L_Newss>("L_Newss");
                }
                return _L_Newss;
            }
        }
        private ObjectSet<L_Newss> _L_Newss;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<L_RForm> L_RForm
        {
            get
            {
                if ((_L_RForm == null))
                {
                    _L_RForm = base.CreateObjectSet<L_RForm>("L_RForm");
                }
                return _L_RForm;
            }
        }
        private ObjectSet<L_RForm> _L_RForm;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<L_Tags> L_Tags
        {
            get
            {
                if ((_L_Tags == null))
                {
                    _L_Tags = base.CreateObjectSet<L_Tags>("L_Tags");
                }
                return _L_Tags;
            }
        }
        private ObjectSet<L_Tags> _L_Tags;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Manages> Manages
        {
            get
            {
                if ((_Manages == null))
                {
                    _Manages = base.CreateObjectSet<Manages>("Manages");
                }
                return _Manages;
            }
        }
        private ObjectSet<Manages> _Manages;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<WdBM> WdBM
        {
            get
            {
                if ((_WdBM == null))
                {
                    _WdBM = base.CreateObjectSet<WdBM>("WdBM");
                }
                return _WdBM;
            }
        }
        private ObjectSet<WdBM> _WdBM;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<L_Log> L_Log
        {
            get
            {
                if ((_L_Log == null))
                {
                    _L_Log = base.CreateObjectSet<L_Log>("L_Log");
                }
                return _L_Log;
            }
        }
        private ObjectSet<L_Log> _L_Log;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 L_Classs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToL_Classs(L_Classs l_Classs)
        {
            base.AddObject("L_Classs", l_Classs);
        }
    
        /// <summary>
        /// 用于向 L_Feedback EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToL_Feedback(L_Feedback l_Feedback)
        {
            base.AddObject("L_Feedback", l_Feedback);
        }
    
        /// <summary>
        /// 用于向 L_Form EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToL_Form(L_Form l_Form)
        {
            base.AddObject("L_Form", l_Form);
        }
    
        /// <summary>
        /// 用于向 L_Newss EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToL_Newss(L_Newss l_Newss)
        {
            base.AddObject("L_Newss", l_Newss);
        }
    
        /// <summary>
        /// 用于向 L_RForm EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToL_RForm(L_RForm l_RForm)
        {
            base.AddObject("L_RForm", l_RForm);
        }
    
        /// <summary>
        /// 用于向 L_Tags EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToL_Tags(L_Tags l_Tags)
        {
            base.AddObject("L_Tags", l_Tags);
        }
    
        /// <summary>
        /// 用于向 Manages EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToManages(Manages manages)
        {
            base.AddObject("Manages", manages);
        }
    
        /// <summary>
        /// 用于向 WdBM EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWdBM(WdBM wdBM)
        {
            base.AddObject("WdBM", wdBM);
        }
    
        /// <summary>
        /// 用于向 L_Log EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToL_Log(L_Log l_Log)
        {
            base.AddObject("L_Log", l_Log);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="L_Classs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class L_Classs : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 L_Classs 对象。
        /// </summary>
        /// <param name="cID">CID 属性的初始值。</param>
        public static L_Classs CreateL_Classs(global::System.Int64 cID)
        {
            L_Classs l_Classs = new L_Classs();
            l_Classs.CID = cID;
            return l_Classs;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CID
        {
            get
            {
                return _CID;
            }
            set
            {
                if (_CID != value)
                {
                    OnCIDChanging(value);
                    ReportPropertyChanging("CID");
                    _CID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CID");
                    OnCIDChanged();
                }
            }
        }
        private global::System.Int64 _CID;
        partial void OnCIDChanging(global::System.Int64 value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CNmae
        {
            get
            {
                return _CNmae;
            }
            set
            {
                OnCNmaeChanging(value);
                ReportPropertyChanging("CNmae");
                _CNmae = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CNmae");
                OnCNmaeChanged();
            }
        }
        private global::System.String _CNmae;
        partial void OnCNmaeChanging(global::System.String value);
        partial void OnCNmaeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CpareID
        {
            get
            {
                return _CpareID;
            }
            set
            {
                OnCpareIDChanging(value);
                ReportPropertyChanging("CpareID");
                _CpareID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CpareID");
                OnCpareIDChanged();
            }
        }
        private Nullable<global::System.Int16> _CpareID;
        partial void OnCpareIDChanging(Nullable<global::System.Int16> value);
        partial void OnCpareIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CKeyWord
        {
            get
            {
                return _CKeyWord;
            }
            set
            {
                OnCKeyWordChanging(value);
                ReportPropertyChanging("CKeyWord");
                _CKeyWord = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CKeyWord");
                OnCKeyWordChanged();
            }
        }
        private global::System.String _CKeyWord;
        partial void OnCKeyWordChanging(global::System.String value);
        partial void OnCKeyWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUrl
        {
            get
            {
                return _CUrl;
            }
            set
            {
                OnCUrlChanging(value);
                ReportPropertyChanging("CUrl");
                _CUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CUrl");
                OnCUrlChanged();
            }
        }
        private global::System.String _CUrl;
        partial void OnCUrlChanging(global::System.String value);
        partial void OnCUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CTag
        {
            get
            {
                return _CTag;
            }
            set
            {
                OnCTagChanging(value);
                ReportPropertyChanging("CTag");
                _CTag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CTag");
                OnCTagChanged();
            }
        }
        private global::System.String _CTag;
        partial void OnCTagChanging(global::System.String value);
        partial void OnCTagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CTag2
        {
            get
            {
                return _CTag2;
            }
            set
            {
                OnCTag2Changing(value);
                ReportPropertyChanging("CTag2");
                _CTag2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CTag2");
                OnCTag2Changed();
            }
        }
        private global::System.String _CTag2;
        partial void OnCTag2Changing(global::System.String value);
        partial void OnCTag2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CTag3
        {
            get
            {
                return _CTag3;
            }
            set
            {
                OnCTag3Changing(value);
                ReportPropertyChanging("CTag3");
                _CTag3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CTag3");
                OnCTag3Changed();
            }
        }
        private global::System.String _CTag3;
        partial void OnCTag3Changing(global::System.String value);
        partial void OnCTag3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CType
        {
            get
            {
                return _CType;
            }
            set
            {
                OnCTypeChanging(value);
                ReportPropertyChanging("CType");
                _CType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CType");
                OnCTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _CType;
        partial void OnCTypeChanging(Nullable<global::System.Int32> value);
        partial void OnCTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CSubSkin
        {
            get
            {
                return _CSubSkin;
            }
            set
            {
                OnCSubSkinChanging(value);
                ReportPropertyChanging("CSubSkin");
                _CSubSkin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CSubSkin");
                OnCSubSkinChanged();
            }
        }
        private global::System.String _CSubSkin;
        partial void OnCSubSkinChanging(global::System.String value);
        partial void OnCSubSkinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CSkin
        {
            get
            {
                return _CSkin;
            }
            set
            {
                OnCSkinChanging(value);
                ReportPropertyChanging("CSkin");
                _CSkin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CSkin");
                OnCSkinChanged();
            }
        }
        private global::System.String _CSkin;
        partial void OnCSkinChanging(global::System.String value);
        partial void OnCSkinChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="L_Feedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class L_Feedback : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 L_Feedback 对象。
        /// </summary>
        /// <param name="fID">FID 属性的初始值。</param>
        public static L_Feedback CreateL_Feedback(global::System.Int64 fID)
        {
            L_Feedback l_Feedback = new L_Feedback();
            l_Feedback.FID = fID;
            return l_Feedback;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FID
        {
            get
            {
                return _FID;
            }
            set
            {
                if (_FID != value)
                {
                    OnFIDChanging(value);
                    ReportPropertyChanging("FID");
                    _FID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FID");
                    OnFIDChanged();
                }
            }
        }
        private global::System.Int64 _FID;
        partial void OnFIDChanging(global::System.Int64 value);
        partial void OnFIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> NID
        {
            get
            {
                return _NID;
            }
            set
            {
                OnNIDChanging(value);
                ReportPropertyChanging("NID");
                _NID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NID");
                OnNIDChanged();
            }
        }
        private Nullable<global::System.Int64> _NID;
        partial void OnNIDChanging(Nullable<global::System.Int64> value);
        partial void OnNIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FName
        {
            get
            {
                return _FName;
            }
            set
            {
                OnFNameChanging(value);
                ReportPropertyChanging("FName");
                _FName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FName");
                OnFNameChanged();
            }
        }
        private global::System.String _FName;
        partial void OnFNameChanging(global::System.String value);
        partial void OnFNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FTel
        {
            get
            {
                return _FTel;
            }
            set
            {
                OnFTelChanging(value);
                ReportPropertyChanging("FTel");
                _FTel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FTel");
                OnFTelChanged();
            }
        }
        private global::System.String _FTel;
        partial void OnFTelChanging(global::System.String value);
        partial void OnFTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FQQ
        {
            get
            {
                return _FQQ;
            }
            set
            {
                OnFQQChanging(value);
                ReportPropertyChanging("FQQ");
                _FQQ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FQQ");
                OnFQQChanged();
            }
        }
        private global::System.String _FQQ;
        partial void OnFQQChanging(global::System.String value);
        partial void OnFQQChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMail
        {
            get
            {
                return _FMail;
            }
            set
            {
                OnFMailChanging(value);
                ReportPropertyChanging("FMail");
                _FMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMail");
                OnFMailChanged();
            }
        }
        private global::System.String _FMail;
        partial void OnFMailChanging(global::System.String value);
        partial void OnFMailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FTitle
        {
            get
            {
                return _FTitle;
            }
            set
            {
                OnFTitleChanging(value);
                ReportPropertyChanging("FTitle");
                _FTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FTitle");
                OnFTitleChanged();
            }
        }
        private global::System.String _FTitle;
        partial void OnFTitleChanging(global::System.String value);
        partial void OnFTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FContent
        {
            get
            {
                return _FContent;
            }
            set
            {
                OnFContentChanging(value);
                ReportPropertyChanging("FContent");
                _FContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FContent");
                OnFContentChanged();
            }
        }
        private global::System.String _FContent;
        partial void OnFContentChanging(global::System.String value);
        partial void OnFContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FTime
        {
            get
            {
                return _FTime;
            }
            set
            {
                OnFTimeChanging(value);
                ReportPropertyChanging("FTime");
                _FTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FTime");
                OnFTimeChanged();
            }
        }
        private global::System.String _FTime;
        partial void OnFTimeChanging(global::System.String value);
        partial void OnFTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FReContent
        {
            get
            {
                return _FReContent;
            }
            set
            {
                OnFReContentChanging(value);
                ReportPropertyChanging("FReContent");
                _FReContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FReContent");
                OnFReContentChanged();
            }
        }
        private global::System.String _FReContent;
        partial void OnFReContentChanging(global::System.String value);
        partial void OnFReContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FReTime
        {
            get
            {
                return _FReTime;
            }
            set
            {
                OnFReTimeChanging(value);
                ReportPropertyChanging("FReTime");
                _FReTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FReTime");
                OnFReTimeChanged();
            }
        }
        private global::System.String _FReTime;
        partial void OnFReTimeChanging(global::System.String value);
        partial void OnFReTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FLock
        {
            get
            {
                return _FLock;
            }
            set
            {
                OnFLockChanging(value);
                ReportPropertyChanging("FLock");
                _FLock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FLock");
                OnFLockChanged();
            }
        }
        private global::System.String _FLock;
        partial void OnFLockChanging(global::System.String value);
        partial void OnFLockChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="L_Form")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class L_Form : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 L_Form 对象。
        /// </summary>
        /// <param name="fID">FID 属性的初始值。</param>
        public static L_Form CreateL_Form(global::System.Int64 fID)
        {
            L_Form l_Form = new L_Form();
            l_Form.FID = fID;
            return l_Form;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FID
        {
            get
            {
                return _FID;
            }
            set
            {
                if (_FID != value)
                {
                    OnFIDChanging(value);
                    ReportPropertyChanging("FID");
                    _FID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FID");
                    OnFIDChanged();
                }
            }
        }
        private global::System.Int64 _FID;
        partial void OnFIDChanging(global::System.Int64 value);
        partial void OnFIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FNmae
        {
            get
            {
                return _FNmae;
            }
            set
            {
                OnFNmaeChanging(value);
                ReportPropertyChanging("FNmae");
                _FNmae = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FNmae");
                OnFNmaeChanged();
            }
        }
        private global::System.String _FNmae;
        partial void OnFNmaeChanging(global::System.String value);
        partial void OnFNmaeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FStat
        {
            get
            {
                return _FStat;
            }
            set
            {
                OnFStatChanging(value);
                ReportPropertyChanging("FStat");
                _FStat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FStat");
                OnFStatChanged();
            }
        }
        private Nullable<global::System.Int64> _FStat;
        partial void OnFStatChanging(Nullable<global::System.Int64> value);
        partial void OnFStatChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fother
        {
            get
            {
                return _Fother;
            }
            set
            {
                OnFotherChanging(value);
                ReportPropertyChanging("Fother");
                _Fother = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fother");
                OnFotherChanged();
            }
        }
        private global::System.String _Fother;
        partial void OnFotherChanging(global::System.String value);
        partial void OnFotherChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String F1
        {
            get
            {
                return _F1;
            }
            set
            {
                OnF1Changing(value);
                ReportPropertyChanging("F1");
                _F1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("F1");
                OnF1Changed();
            }
        }
        private global::System.String _F1;
        partial void OnF1Changing(global::System.String value);
        partial void OnF1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FMust
        {
            get
            {
                return _FMust;
            }
            set
            {
                OnFMustChanging(value);
                ReportPropertyChanging("FMust");
                _FMust = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FMust");
                OnFMustChanged();
            }
        }
        private Nullable<global::System.Int64> _FMust;
        partial void OnFMustChanging(Nullable<global::System.Int64> value);
        partial void OnFMustChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FTime
        {
            get
            {
                return _FTime;
            }
            set
            {
                OnFTimeChanging(value);
                ReportPropertyChanging("FTime");
                _FTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FTime");
                OnFTimeChanged();
            }
        }
        private global::System.String _FTime;
        partial void OnFTimeChanging(global::System.String value);
        partial void OnFTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String F1C
        {
            get
            {
                return _F1C;
            }
            set
            {
                OnF1CChanging(value);
                ReportPropertyChanging("F1C");
                _F1C = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("F1C");
                OnF1CChanged();
            }
        }
        private global::System.String _F1C;
        partial void OnF1CChanging(global::System.String value);
        partial void OnF1CChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="L_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class L_Log : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 L_Log 对象。
        /// </summary>
        /// <param name="lID">LID 属性的初始值。</param>
        public static L_Log CreateL_Log(global::System.Int64 lID)
        {
            L_Log l_Log = new L_Log();
            l_Log.LID = lID;
            return l_Log;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 LID
        {
            get
            {
                return _LID;
            }
            set
            {
                if (_LID != value)
                {
                    OnLIDChanging(value);
                    ReportPropertyChanging("LID");
                    _LID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LID");
                    OnLIDChanged();
                }
            }
        }
        private global::System.Int64 _LID;
        partial void OnLIDChanging(global::System.Int64 value);
        partial void OnLIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String L_TiTLE
        {
            get
            {
                return _L_TiTLE;
            }
            set
            {
                OnL_TiTLEChanging(value);
                ReportPropertyChanging("L_TiTLE");
                _L_TiTLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("L_TiTLE");
                OnL_TiTLEChanged();
            }
        }
        private global::System.String _L_TiTLE;
        partial void OnL_TiTLEChanging(global::System.String value);
        partial void OnL_TiTLEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String L_IP
        {
            get
            {
                return _L_IP;
            }
            set
            {
                OnL_IPChanging(value);
                ReportPropertyChanging("L_IP");
                _L_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("L_IP");
                OnL_IPChanged();
            }
        }
        private global::System.String _L_IP;
        partial void OnL_IPChanging(global::System.String value);
        partial void OnL_IPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String L_Time
        {
            get
            {
                return _L_Time;
            }
            set
            {
                OnL_TimeChanging(value);
                ReportPropertyChanging("L_Time");
                _L_Time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("L_Time");
                OnL_TimeChanged();
            }
        }
        private global::System.String _L_Time;
        partial void OnL_TimeChanging(global::System.String value);
        partial void OnL_TimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String L_Act
        {
            get
            {
                return _L_Act;
            }
            set
            {
                OnL_ActChanging(value);
                ReportPropertyChanging("L_Act");
                _L_Act = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("L_Act");
                OnL_ActChanged();
            }
        }
        private global::System.String _L_Act;
        partial void OnL_ActChanging(global::System.String value);
        partial void OnL_ActChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String L_UID
        {
            get
            {
                return _L_UID;
            }
            set
            {
                OnL_UIDChanging(value);
                ReportPropertyChanging("L_UID");
                _L_UID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("L_UID");
                OnL_UIDChanged();
            }
        }
        private global::System.String _L_UID;
        partial void OnL_UIDChanging(global::System.String value);
        partial void OnL_UIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="L_Newss")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class L_Newss : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 L_Newss 对象。
        /// </summary>
        /// <param name="nID">NID 属性的初始值。</param>
        public static L_Newss CreateL_Newss(global::System.Int64 nID)
        {
            L_Newss l_Newss = new L_Newss();
            l_Newss.NID = nID;
            return l_Newss;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 NID
        {
            get
            {
                return _NID;
            }
            set
            {
                if (_NID != value)
                {
                    OnNIDChanging(value);
                    ReportPropertyChanging("NID");
                    _NID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NID");
                    OnNIDChanged();
                }
            }
        }
        private global::System.Int64 _NID;
        partial void OnNIDChanging(global::System.Int64 value);
        partial void OnNIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClassId
        {
            get
            {
                return _ClassId;
            }
            set
            {
                OnClassIdChanging(value);
                ReportPropertyChanging("ClassId");
                _ClassId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassId");
                OnClassIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ClassId;
        partial void OnClassIdChanging(Nullable<global::System.Int32> value);
        partial void OnClassIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.String _From;
        partial void OnFromChanging(global::System.String value);
        partial void OnFromChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZhaiYao
        {
            get
            {
                return _ZhaiYao;
            }
            set
            {
                OnZhaiYaoChanging(value);
                ReportPropertyChanging("ZhaiYao");
                _ZhaiYao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZhaiYao");
                OnZhaiYaoChanged();
            }
        }
        private global::System.String _ZhaiYao;
        partial void OnZhaiYaoChanging(global::System.String value);
        partial void OnZhaiYaoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Img
        {
            get
            {
                return _Img;
            }
            set
            {
                OnImgChanging(value);
                ReportPropertyChanging("Img");
                _Img = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Img");
                OnImgChanged();
            }
        }
        private global::System.String _Img;
        partial void OnImgChanging(global::System.String value);
        partial void OnImgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Click
        {
            get
            {
                return _Click;
            }
            set
            {
                OnClickChanging(value);
                ReportPropertyChanging("Click");
                _Click = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Click");
                OnClickChanged();
            }
        }
        private global::System.String _Click;
        partial void OnClickChanging(global::System.String value);
        partial void OnClickChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Time;
        partial void OnTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsTop
        {
            get
            {
                return _IsTop;
            }
            set
            {
                OnIsTopChanging(value);
                ReportPropertyChanging("IsTop");
                _IsTop = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsTop");
                OnIsTopChanged();
            }
        }
        private global::System.String _IsTop;
        partial void OnIsTopChanging(global::System.String value);
        partial void OnIsTopChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsHot
        {
            get
            {
                return _IsHot;
            }
            set
            {
                OnIsHotChanging(value);
                ReportPropertyChanging("IsHot");
                _IsHot = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsHot");
                OnIsHotChanged();
            }
        }
        private global::System.String _IsHot;
        partial void OnIsHotChanging(global::System.String value);
        partial void OnIsHotChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsSlide
        {
            get
            {
                return _IsSlide;
            }
            set
            {
                OnIsSlideChanging(value);
                ReportPropertyChanging("IsSlide");
                _IsSlide = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsSlide");
                OnIsSlideChanged();
            }
        }
        private global::System.String _IsSlide;
        partial void OnIsSlideChanging(global::System.String value);
        partial void OnIsSlideChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsLock
        {
            get
            {
                return _IsLock;
            }
            set
            {
                OnIsLockChanging(value);
                ReportPropertyChanging("IsLock");
                _IsLock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsLock");
                OnIsLockChanged();
            }
        }
        private global::System.String _IsLock;
        partial void OnIsLockChanging(global::System.String value);
        partial void OnIsLockChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsRed
        {
            get
            {
                return _IsRed;
            }
            set
            {
                OnIsRedChanging(value);
                ReportPropertyChanging("IsRed");
                _IsRed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsRed");
                OnIsRedChanged();
            }
        }
        private global::System.String _IsRed;
        partial void OnIsRedChanging(global::System.String value);
        partial void OnIsRedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="L_RForm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class L_RForm : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 L_RForm 对象。
        /// </summary>
        /// <param name="frID">FrID 属性的初始值。</param>
        public static L_RForm CreateL_RForm(global::System.Int64 frID)
        {
            L_RForm l_RForm = new L_RForm();
            l_RForm.FrID = frID;
            return l_RForm;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FrID
        {
            get
            {
                return _FrID;
            }
            set
            {
                if (_FrID != value)
                {
                    OnFrIDChanging(value);
                    ReportPropertyChanging("FrID");
                    _FrID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FrID");
                    OnFrIDChanged();
                }
            }
        }
        private global::System.Int64 _FrID;
        partial void OnFrIDChanging(global::System.Int64 value);
        partial void OnFrIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FrName
        {
            get
            {
                return _FrName;
            }
            set
            {
                OnFrNameChanging(value);
                ReportPropertyChanging("FrName");
                _FrName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FrName");
                OnFrNameChanged();
            }
        }
        private global::System.String _FrName;
        partial void OnFrNameChanging(global::System.String value);
        partial void OnFrNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fr1
        {
            get
            {
                return _Fr1;
            }
            set
            {
                OnFr1Changing(value);
                ReportPropertyChanging("Fr1");
                _Fr1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fr1");
                OnFr1Changed();
            }
        }
        private global::System.String _Fr1;
        partial void OnFr1Changing(global::System.String value);
        partial void OnFr1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fr2
        {
            get
            {
                return _Fr2;
            }
            set
            {
                OnFr2Changing(value);
                ReportPropertyChanging("Fr2");
                _Fr2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fr2");
                OnFr2Changed();
            }
        }
        private global::System.String _Fr2;
        partial void OnFr2Changing(global::System.String value);
        partial void OnFr2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FrTime
        {
            get
            {
                return _FrTime;
            }
            set
            {
                OnFrTimeChanging(value);
                ReportPropertyChanging("FrTime");
                _FrTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FrTime");
                OnFrTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FrTime;
        partial void OnFrTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFrTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FrRepaly
        {
            get
            {
                return _FrRepaly;
            }
            set
            {
                OnFrRepalyChanging(value);
                ReportPropertyChanging("FrRepaly");
                _FrRepaly = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FrRepaly");
                OnFrRepalyChanged();
            }
        }
        private global::System.String _FrRepaly;
        partial void OnFrRepalyChanging(global::System.String value);
        partial void OnFrRepalyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FrReOk
        {
            get
            {
                return _FrReOk;
            }
            set
            {
                OnFrReOkChanging(value);
                ReportPropertyChanging("FrReOk");
                _FrReOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FrReOk");
                OnFrReOkChanged();
            }
        }
        private Nullable<global::System.Int64> _FrReOk;
        partial void OnFrReOkChanging(Nullable<global::System.Int64> value);
        partial void OnFrReOkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FrReTime
        {
            get
            {
                return _FrReTime;
            }
            set
            {
                OnFrReTimeChanging(value);
                ReportPropertyChanging("FrReTime");
                _FrReTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FrReTime");
                OnFrReTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _FrReTime;
        partial void OnFrReTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnFrReTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fr1c
        {
            get
            {
                return _Fr1c;
            }
            set
            {
                OnFr1cChanging(value);
                ReportPropertyChanging("Fr1c");
                _Fr1c = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fr1c");
                OnFr1cChanged();
            }
        }
        private global::System.String _Fr1c;
        partial void OnFr1cChanging(global::System.String value);
        partial void OnFr1cChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fr2c
        {
            get
            {
                return _Fr2c;
            }
            set
            {
                OnFr2cChanging(value);
                ReportPropertyChanging("Fr2c");
                _Fr2c = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fr2c");
                OnFr2cChanged();
            }
        }
        private global::System.String _Fr2c;
        partial void OnFr2cChanging(global::System.String value);
        partial void OnFr2cChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FID
        {
            get
            {
                return _FID;
            }
            set
            {
                OnFIDChanging(value);
                ReportPropertyChanging("FID");
                _FID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FID");
                OnFIDChanged();
            }
        }
        private Nullable<global::System.Int64> _FID;
        partial void OnFIDChanging(Nullable<global::System.Int64> value);
        partial void OnFIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="L_Tags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class L_Tags : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 L_Tags 对象。
        /// </summary>
        /// <param name="tID">TID 属性的初始值。</param>
        public static L_Tags CreateL_Tags(global::System.Int64 tID)
        {
            L_Tags l_Tags = new L_Tags();
            l_Tags.TID = tID;
            return l_Tags;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TID
        {
            get
            {
                return _TID;
            }
            set
            {
                if (_TID != value)
                {
                    OnTIDChanging(value);
                    ReportPropertyChanging("TID");
                    _TID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TID");
                    OnTIDChanged();
                }
            }
        }
        private global::System.Int64 _TID;
        partial void OnTIDChanging(global::System.Int64 value);
        partial void OnTIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TName
        {
            get
            {
                return _TName;
            }
            set
            {
                OnTNameChanging(value);
                ReportPropertyChanging("TName");
                _TName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TName");
                OnTNameChanged();
            }
        }
        private global::System.String _TName;
        partial void OnTNameChanging(global::System.String value);
        partial void OnTNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TContent
        {
            get
            {
                return _TContent;
            }
            set
            {
                OnTContentChanging(value);
                ReportPropertyChanging("TContent");
                _TContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TContent");
                OnTContentChanged();
            }
        }
        private global::System.String _TContent;
        partial void OnTContentChanging(global::System.String value);
        partial void OnTContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TNotice
        {
            get
            {
                return _TNotice;
            }
            set
            {
                OnTNoticeChanging(value);
                ReportPropertyChanging("TNotice");
                _TNotice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TNotice");
                OnTNoticeChanged();
            }
        }
        private global::System.String _TNotice;
        partial void OnTNoticeChanging(global::System.String value);
        partial void OnTNoticeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Manages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Manages : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Manages 对象。
        /// </summary>
        /// <param name="mID">MID 属性的初始值。</param>
        public static Manages CreateManages(global::System.Int64 mID)
        {
            Manages manages = new Manages();
            manages.MID = mID;
            return manages;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 MID
        {
            get
            {
                return _MID;
            }
            set
            {
                if (_MID != value)
                {
                    OnMIDChanging(value);
                    ReportPropertyChanging("MID");
                    _MID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MID");
                    OnMIDChanged();
                }
            }
        }
        private global::System.Int64 _MID;
        partial void OnMIDChanging(global::System.Int64 value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MName
        {
            get
            {
                return _MName;
            }
            set
            {
                OnMNameChanging(value);
                ReportPropertyChanging("MName");
                _MName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MName");
                OnMNameChanged();
            }
        }
        private global::System.String _MName;
        partial void OnMNameChanging(global::System.String value);
        partial void OnMNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MPWD
        {
            get
            {
                return _MPWD;
            }
            set
            {
                OnMPWDChanging(value);
                ReportPropertyChanging("MPWD");
                _MPWD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MPWD");
                OnMPWDChanged();
            }
        }
        private global::System.String _MPWD;
        partial void OnMPWDChanging(global::System.String value);
        partial void OnMPWDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MRole
        {
            get
            {
                return _MRole;
            }
            set
            {
                OnMRoleChanging(value);
                ReportPropertyChanging("MRole");
                _MRole = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MRole");
                OnMRoleChanged();
            }
        }
        private global::System.String _MRole;
        partial void OnMRoleChanging(global::System.String value);
        partial void OnMRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MPower
        {
            get
            {
                return _MPower;
            }
            set
            {
                OnMPowerChanging(value);
                ReportPropertyChanging("MPower");
                _MPower = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MPower");
                OnMPowerChanged();
            }
        }
        private global::System.String _MPower;
        partial void OnMPowerChanging(global::System.String value);
        partial void OnMPowerChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="WdBM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WdBM : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 WdBM 对象。
        /// </summary>
        /// <param name="bID">BID 属性的初始值。</param>
        public static WdBM CreateWdBM(global::System.Int64 bID)
        {
            WdBM wdBM = new WdBM();
            wdBM.BID = bID;
            return wdBM;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 BID
        {
            get
            {
                return _BID;
            }
            set
            {
                if (_BID != value)
                {
                    OnBIDChanging(value);
                    ReportPropertyChanging("BID");
                    _BID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BID");
                    OnBIDChanged();
                }
            }
        }
        private global::System.Int64 _BID;
        partial void OnBIDChanging(global::System.Int64 value);
        partial void OnBIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bname
        {
            get
            {
                return _Bname;
            }
            set
            {
                OnBnameChanging(value);
                ReportPropertyChanging("Bname");
                _Bname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bname");
                OnBnameChanged();
            }
        }
        private global::System.String _Bname;
        partial void OnBnameChanging(global::System.String value);
        partial void OnBnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Btel
        {
            get
            {
                return _Btel;
            }
            set
            {
                OnBtelChanging(value);
                ReportPropertyChanging("Btel");
                _Btel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Btel");
                OnBtelChanged();
            }
        }
        private global::System.String _Btel;
        partial void OnBtelChanging(global::System.String value);
        partial void OnBtelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Biden
        {
            get
            {
                return _Biden;
            }
            set
            {
                OnBidenChanging(value);
                ReportPropertyChanging("Biden");
                _Biden = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Biden");
                OnBidenChanged();
            }
        }
        private global::System.String _Biden;
        partial void OnBidenChanging(global::System.String value);
        partial void OnBidenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bcom
        {
            get
            {
                return _Bcom;
            }
            set
            {
                OnBcomChanging(value);
                ReportPropertyChanging("Bcom");
                _Bcom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bcom");
                OnBcomChanged();
            }
        }
        private global::System.String _Bcom;
        partial void OnBcomChanging(global::System.String value);
        partial void OnBcomChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bmail
        {
            get
            {
                return _Bmail;
            }
            set
            {
                OnBmailChanging(value);
                ReportPropertyChanging("Bmail");
                _Bmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bmail");
                OnBmailChanged();
            }
        }
        private global::System.String _Bmail;
        partial void OnBmailChanging(global::System.String value);
        partial void OnBmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bname2
        {
            get
            {
                return _Bname2;
            }
            set
            {
                OnBname2Changing(value);
                ReportPropertyChanging("Bname2");
                _Bname2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bname2");
                OnBname2Changed();
            }
        }
        private global::System.String _Bname2;
        partial void OnBname2Changing(global::System.String value);
        partial void OnBname2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Btel2
        {
            get
            {
                return _Btel2;
            }
            set
            {
                OnBtel2Changing(value);
                ReportPropertyChanging("Btel2");
                _Btel2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Btel2");
                OnBtel2Changed();
            }
        }
        private global::System.String _Btel2;
        partial void OnBtel2Changing(global::System.String value);
        partial void OnBtel2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Biden2
        {
            get
            {
                return _Biden2;
            }
            set
            {
                OnBiden2Changing(value);
                ReportPropertyChanging("Biden2");
                _Biden2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Biden2");
                OnBiden2Changed();
            }
        }
        private global::System.String _Biden2;
        partial void OnBiden2Changing(global::System.String value);
        partial void OnBiden2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bcom2
        {
            get
            {
                return _Bcom2;
            }
            set
            {
                OnBcom2Changing(value);
                ReportPropertyChanging("Bcom2");
                _Bcom2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bcom2");
                OnBcom2Changed();
            }
        }
        private global::System.String _Bcom2;
        partial void OnBcom2Changing(global::System.String value);
        partial void OnBcom2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bmail2
        {
            get
            {
                return _Bmail2;
            }
            set
            {
                OnBmail2Changing(value);
                ReportPropertyChanging("Bmail2");
                _Bmail2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bmail2");
                OnBmail2Changed();
            }
        }
        private global::System.String _Bmail2;
        partial void OnBmail2Changing(global::System.String value);
        partial void OnBmail2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bimg
        {
            get
            {
                return _Bimg;
            }
            set
            {
                OnBimgChanging(value);
                ReportPropertyChanging("Bimg");
                _Bimg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bimg");
                OnBimgChanged();
            }
        }
        private global::System.String _Bimg;
        partial void OnBimgChanging(global::System.String value);
        partial void OnBimgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bimg2
        {
            get
            {
                return _Bimg2;
            }
            set
            {
                OnBimg2Changing(value);
                ReportPropertyChanging("Bimg2");
                _Bimg2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bimg2");
                OnBimg2Changed();
            }
        }
        private global::System.String _Bimg2;
        partial void OnBimg2Changing(global::System.String value);
        partial void OnBimg2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Btime
        {
            get
            {
                return _Btime;
            }
            set
            {
                OnBtimeChanging(value);
                ReportPropertyChanging("Btime");
                _Btime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Btime");
                OnBtimeChanged();
            }
        }
        private global::System.String _Btime;
        partial void OnBtimeChanging(global::System.String value);
        partial void OnBtimeChanged();

        #endregion
    
    }

    #endregion
    

